xcopy  ..\StuntrallyData\cars ..\x64\Release\cars /e /i /h
xcopy  ..\StuntrallyData\carsim ..\x64\Release\carsim /e /i /h
xcopy  ..\StuntrallyData\compositor ..\x64\Release\compositor /e /i /h
xcopy  ..\StuntrallyData\editor ..\x64\Release\editor /e /i /h
xcopy  ..\StuntrallyData\fonts ..\x64\Release\fonts /e /i /h
xcopy  ..\StuntrallyData\ghosts ..\x64\Release\ghosts /e /i /h
xcopy  ..\StuntrallyData\grass ..\x64\Release\grass /e /i /h
xcopy  ..\StuntrallyData\gui ..\x64\Release\gui /e /i /h
xcopy  ..\StuntrallyData\hud ..\x64\Release\hud /e /i /h
xcopy  ..\StuntrallyData\lessons ..\x64\Release\lessons /e /i /h
xcopy  ..\StuntrallyData\loading ..\x64\Release\loading /e /i /h
xcopy  ..\StuntrallyData\materials ..\x64\Release\materials /e /i /h
xcopy  ..\StuntrallyData\materials2 ..\x64\Release\materials2 /e /i /h
xcopy  ..\StuntrallyData\objects ..\x64\Release\objects /e /i /h
xcopy  ..\StuntrallyData\objects0 ..\x64\Release\objects0 /e /i /h
xcopy  ..\StuntrallyData\objects2 ..\x64\Release\objects2 /e /i /h
xcopy  ..\StuntrallyData\objectsC ..\x64\Release\objectsC /e /i /h
xcopy  ..\StuntrallyData\particles ..\x64\Release\particles /e /i /h
xcopy  ..\StuntrallyData\road ..\x64\Release\road /e /i /h
xcopy  ..\StuntrallyData\road_s ..\x64\Release\road_s /e /i /h
xcopy  ..\StuntrallyData\rocks ..\x64\Release\rocks /e /i /h
xcopy  ..\StuntrallyData\skies ..\x64\Release\skies /e /i /h
xcopy  ..\StuntrallyData\skies_s ..\x64\Release\skies_s /e /i /h
xcopy  ..\StuntrallyData\sounds ..\x64\Release\sounds /e /i /h
xcopy  ..\StuntrallyData\terrain ..\x64\Release\terrain /e /i /h
xcopy  ..\StuntrallyData\terrain_s ..\x64\Release\terrain_s /e /i /h
xcopy  ..\StuntrallyData\tracks ..\x64\Release\tracks /e /i /h
xcopy  ..\StuntrallyData\trees ..\x64\Release\trees /e /i /h
xcopy  ..\StuntrallyData\trees2 ..\x64\Release\trees2 /e /i /h
xcopy  ..\StuntrallyData\trees-old ..\x64\Release\trees-old /e /i /h